@startuml
class BankAccountService {
    + EverydayAccount : BankAccount <<get>> <<set>>
    + SavingsAccount : BankAccount <<get>> <<set>>
    + BankAccountService(BankAccount, BankAccount)
}
@enduml
